[project]
name = "applied_data_science"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "", email = ""},
]
dependencies = [
    "accelerate==0.29.2",
    "auto-gptq==0.7.1",
    "chromadb==0.4.5",
    "datasets==2.18.0",
    "gensim==4.3.2",
    "gekko==1.1.1",
    "huggingface-hub==0.21.4",
    "jsonlines==4.0.0",
    "langchain==0.1.16",
    "matplotlib==3.8.3",
    "nltk==3.8.1",
    "numpy==1.24.4",
    "openai==0.27.4",
    "pandas==2.2.2",
    "packaging==24.0",
    "parameterized==0.9.0",
    "pdfminer-six==20231228",
    "plotly==5.20.0",
    "pyLDAvis==3.4.1",
    "pypdf==4.2.0",
    "spacy==2.3.9",
    "tika==2.6.0",
    "torch==1.13.1+cu116",
    "transformers==4.35.2",
    "tqdm==4.66.2",
    "rouge==1.0.1",
    "safetensors==0.4.2",
    "setuptools==68.2.2",
    "wordcloud==1.9.3",
    "jq",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = false
